"""empty message

Revision ID: 0cd2c8b54d7f
Revises: 9f501311e5a6
Create Date: 2023-07-27 11:50:47.516440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cd2c8b54d7f'
down_revision = '9f501311e5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('ctf_name', sa.String(length=128), nullable=True))
    op.add_column('certificate', sa.Column('team_place', sa.Integer(), nullable=True))
    op.add_column('certificate', sa.Column('user_place', sa.Integer(), nullable=True))
    op.drop_column('certificate', 'place')
    op.drop_column('certificate', 'challenge_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('challenge_name', sa.VARCHAR(length=128), nullable=True))
    op.add_column('certificate', sa.Column('place', sa.INTEGER(), nullable=True))
    op.drop_column('certificate', 'user_place')
    op.drop_column('certificate', 'team_place')
    op.drop_column('certificate', 'ctf_name')
    # ### end Alembic commands ###
