"""empty message

Revision ID: 375ae3b918d5
Revises: 3f46e534d78d
Create Date: 2023-08-04 17:11:59.442320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375ae3b918d5'
down_revision = '3f46e534d78d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'certificate', ['saved_cert_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    # ### end Alembic commands ###
