"""Add cert_id column to users table

Revision ID: 3f46e534d78d
Revises: 0cd2c8b54d7f
Create Date: 2023-08-04 15:57:09.755862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f46e534d78d'
down_revision = '0cd2c8b54d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'users', 'certificate', ['cert_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    # ### end Alembic commands ###
