"""empty message

Revision ID: 6f29403e170f
Revises: 12957694d907
Create Date: 2023-07-20 16:35:37.764791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f29403e170f'
down_revision = '12957694d907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('rank', sa.Integer(), nullable=True))
    op.add_column('certificate', sa.Column('team_name', sa.String(length=128), nullable=True))
    op.drop_column('certificate', 'obtained_score')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificate', sa.Column('obtained_score', sa.INTEGER(), nullable=True))
    op.drop_column('certificate', 'team_name')
    op.drop_column('certificate', 'rank')
    # ### end Alembic commands ###
